# Generated by Django 5.1.4 on 2025-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_author_alter_product_category_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(default='6.25 × 9.25 inches', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(default='Hardcover', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(default='000-0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
