# Generated by Django 5.1.4 on 2025-05-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_dimensions_product_format_product_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FI', 'Fiction'), ('NF', 'Non-Fiction'), ('SF', 'Science-Fiction'), ('HI', 'History'), ('FA', 'Fantasy')], max_length=2),
        ),
    ]
